In [29]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['titanic', 'iriscsv']

In [30]:
import os
print(os.listdir("../input"))
import pandas as pd

['titanic', 'iriscsv']

In [85]:
df_iris = pd.read_csv("../input/iriscsv/Iris.csv")

In [86]:
df_iris.shape

(150, 6)

In [87]:
df_iris.head()

   Id  SepalLengthCm     ...       PetalWidthCm      Species
0   1            5.1     ...                0.2  Iris-setosa
1   2            4.9     ...                0.2  Iris-setosa
2   3            4.7     ...                0.2  Iris-setosa
3   4            4.6     ...                0.2  Iris-setosa
4   5            5.0     ...                0.2  Iris-setosa

[5 rows x 6 columns]

In [88]:
df_iris.drop(columns=['Id'])

     SepalLengthCm  SepalWidthCm       ...        PetalWidthCm         Species
0              5.1           3.5       ...                 0.2     Iris-setosa
1              4.9           3.0       ...                 0.2     Iris-setosa
2              4.7           3.2       ...                 0.2     Iris-setosa
3              4.6           3.1       ...                 0.2     Iris-setosa
4              5.0           3.6       ...                 0.2     Iris-setosa
5              5.4           3.9       ...                 0.4     Iris-setosa
6              4.6           3.4       ...                 0.3     Iris-setosa
7              5.0           3.4       ...                 0.2     Iris-setosa
8              4.4           2.9       ...                 0.2     Iris-setosa
9              4.9           3.1       ...                 0.1     Iris-setosa
10             5.4           3.7       ...                 0.2     Iris-setosa
11             4.8           3.4       ...                 0.2     Iris-setosa
12             4.8           3.0       ...                 0.1     Iris-setosa
13             4.3           3.0       ...                 0.1     Iris-setosa
14             5.8           4.0       ...                 0.2     Iris-setosa
15             5.7           4.4       ...                 0.4     Iris-setosa
16             5.4           3.9       ...                 0.4     Iris-setosa
17             5.1           3.5       ...                 0.3     Iris-setosa
18             5.7           3.8       ...                 0.3     Iris-setosa
19             5.1           3.8       ...                 0.3     Iris-setosa
20             5.4           3.4       ...                 0.2     Iris-setosa
21             5.1           3.7       ...                 0.4     Iris-setosa
22             4.6           3.6       ...                 0.2     Iris-setosa
23             5.1           3.3       ...                 0.5     Iris-setosa
24             4.8           3.4       ...                 0.2     Iris-setosa
25             5.0           3.0       ...                 0.2     Iris-setosa
26             5.0           3.4       ...                 0.4     Iris-setosa
27             5.2           3.5       ...                 0.2     Iris-setosa
28             5.2           3.4       ...                 0.2     Iris-setosa
29             4.7           3.2       ...                 0.2     Iris-setosa
..             ...           ...       ...                 ...             ...
120            6.9           3.2       ...                 2.3  Iris-virginica
121            5.6           2.8       ...                 2.0  Iris-virginica
122            7.7           2.8       ...                 2.0  Iris-virginica
123            6.3           2.7       ...                 1.8  Iris-virginica
124            6.7           3.3       ...                 2.1  Iris-virginica
125            7.2           3.2       ...                 1.8  Iris-virginica
126            6.2           2.8       ...                 1.8  Iris-virginica
127            6.1           3.0       ...                 1.8  Iris-virginica
128            6.4           2.8       ...                 2.1  Iris-virginica
129            7.2           3.0       ...                 1.6  Iris-virginica
130            7.4           2.8       ...                 1.9  Iris-virginica
131            7.9           3.8       ...                 2.0  Iris-virginica
132            6.4           2.8       ...                 2.2  Iris-virginica
133            6.3           2.8       ...                 1.5  Iris-virginica
134            6.1           2.6       ...                 1.4  Iris-virginica
135            7.7           3.0       ...                 2.3  Iris-virginica
136            6.3           3.4       ...                 2.4  Iris-virginica
137            6.4           3.1       ...                 1.8  Iris-virginica
138            6.0           3.0       ...                 1.8  Iris-virginica
139            6.9           3.1       ...                 2.1  Iris-virginica
140            6.7           3.1       ...                 2.4  Iris-virginica
141            6.9           3.1       ...                 2.3  Iris-virginica
142            5.8           2.7       ...                 1.9  Iris-virginica
143            6.8           3.2       ...                 2.3  Iris-virginica
144            6.7           3.3       ...                 2.5  Iris-virginica
145            6.7           3.0       ...                 2.3  Iris-virginica
146            6.3           2.5       ...                 1.9  Iris-virginica
147            6.5           3.0       ...                 2.0  Iris-virginica
148            6.2           3.4       ...                 2.3  Iris-virginica
149            5.9           3.0       ...                 1.8  Iris-virginica

[150 rows x 5 columns]

In [89]:
# df_iris_new = df_iris[df_iris.add]
df_iris.describe()

               Id  SepalLengthCm      ...       PetalLengthCm  PetalWidthCm
count  150.000000     150.000000      ...          150.000000    150.000000
mean    75.500000       5.843333      ...            3.758667      1.198667
std     43.445368       0.828066      ...            1.764420      0.763161
min      1.000000       4.300000      ...            1.000000      0.100000
25%     38.250000       5.100000      ...            1.600000      0.300000
50%     75.500000       5.800000      ...            4.350000      1.300000
75%    112.750000       6.400000      ...            5.100000      1.800000
max    150.000000       7.900000      ...            6.900000      2.500000

[8 rows x 5 columns]

In [62]:
# max, min, av in form of df.describe() assignment
# df_iris_setosa = df_iris[df_iris['Species'] == 'iris-setosa']
# df_iris_versicolour = df_iris[df_iris['Species'] == 'iris-versicolour']
# df_iris_virginica = df_iris[df_iris['Species'] == 'iris-virginica']
# http://makemeanalyst.com/basic-statistics-explore-your-data-cases-variables-types-of-variables/

In [93]:
df_iris = df_iris.drop(columns = ["Id"])

KeyError: "['Id'] not found in axis"

In [94]:
df_iris['sum']=df_iris.sum(axis=1)

In [96]:
df_iris.head(5)

   SepalLengthCm  SepalWidthCm  ...       Species   sum
0            5.1           3.5  ...   Iris-setosa  10.2
1            4.9           3.0  ...   Iris-setosa   9.5
2            4.7           3.2  ...   Iris-setosa   9.4
3            4.6           3.1  ...   Iris-setosa   9.4
4            5.0           3.6  ...   Iris-setosa  10.2

[5 rows x 6 columns]

In [99]:
df_iris = df_iris.drop(columns=["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"])

In [101]:
df_iris.head(5)

       Species   sum
0  Iris-setosa  10.2
1  Iris-setosa   9.5
2  Iris-setosa   9.4
3  Iris-setosa   9.4
4  Iris-setosa  10.2

In [103]:
df_iris.groupby("Species")['sum'].describe().reset_index()

           Species  count    mean       std  ...     25%    50%   75%   max
0      Iris-setosa   50.0  10.132  0.789068  ...    9.60  10.20  10.7  12.0
1  Iris-versicolor   50.0  14.292  1.290916  ...   13.45  14.35  15.4  16.4
2   Iris-virginica   50.0  17.140  1.454760  ...   15.80  17.20  18.1  20.4

[3 rows x 9 columns]